version: "3.9"

services:
  answerly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: answerly-app
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - default